### ISSUE TITLE
The sidebar isn’t completely hidden when pressing ⌥⌘E (Close File Browser)

### ISSUE THREAD

**Issue by peterhellberg** [alloy/macvim#20]
# Problem description

The sidebar isn’t visible when starting MacVim.

Closing the sidebar results in the sidebar being resized to a 1 pixel wide (on the left/right hand side depending on the org.vim.MacVim MMDrawerPreferredEdge setting)
## Expected behavior

The sidebar should be completely removed from the interface when closed.

**Comment by alloy** [comment]
I now see that this is because the view isn't really hidden, but rather the part of the split view that the sidebar is in is collapsed. I still agree that it could use some polish, though.

Also, for consistency sake, I wonder if we should always have the collapsed split view and if the user opens it by dragging the splitter the first time it should actually start working.

**Comment by peterhellberg** [comment]
The most annoying thing about this is when you run MacVim in full screen
while using a dark/black theme, you get a bright (white) line along one of
the sides of your monitor.

## 

Peter Hellberg
Web Developer, Code7 Interactive

**Comment by b4winckler** [comment]
I saw the discussion after pushing this fix.  It seems nicer to be able to hide the divider completely, in particular with regards to @peterhellberg's comment about dark backgrounds.  Note that if you drag the divider to the side it will still be visible -- only if you hide the file browser via ⌥⌘E does the divider hide completely.
