### ISSUE TITLE
Provide binary builds for people who don't want to compile (or can't)

### ISSUE THREAD

**Issue by joem** [alloy/macvim#39]
This looks like a great fork, and I know many people who would love to use it if they could just download an app and install it, instead of having to build it from source.

All kinds of people use MacVim, and some are not so comfortable with command-line stuff. (In fact, I think it's fair to say that MacVim itself, and this fork in particular, are more geared towards those people than other, more traditional vim distributions.) Also, although some people may be comfortable with command-line stuff, they may not want to install Developer Tools (or some other form of GCC) just for this fork (ie. web devs, perhaps?).

I'm not sure of exactly what is entailed in making distributable binary builds, so I'm not sure if this request is practical or not, but I thought I'd mention it anyway.

**Comment by joem** [comment]
Oh, silly me... I just found https://github.com/alloy/macvim/downloads mentioned in another issue.

I guess I'll close this issue.

**Comment by alloy** [comment]
Glad you to hear that it might be of some use :)

So yeah, you’ve found the builds. For now these snapshot builds is how it will be, because there’s still enough to do before even figuring out when to merge this back in to the upstream MacVim repo as a proper release. However, I now realize that until that happens I should probably start including the extra files that the upstream maintainer includes in the build archives. E.g. the mvim command-line tool. I’ll do this next time.
