### ISSUE TITLE
Thoughts on default side panel bgcolor.

### ISSUE THREAD

**Issue by jordwalke** [alloy/macvim#47]
I saw some talk about allowing customization of the side bar. I think it's a great idea, but even if you decide not to allow customization right now, could we make the default similar to other mac application sidebars, which have a subtle grey/blue color?
I notice other apps have a background that is approximately RGB(.86,.88,.91), with a single 1px thin vertical line that separates the side panel from the main content with color approximately RGB(.69, .69, .69) though there's no set rules for this.
I'd really love customizability of the color eventually, as I switch between dark and light schemes, and the bright background color is kind of jaring when I have a dark color scheme - I understand we'd need to allow customization of icons/font colors, triangle arrows etc - so it's understandable there's more important milestones.

**Comment by ashgti** [comment]
Would it be possible to get the colors from the current theme?

**Comment by tobia** [comment]
I gave the file browser the same look as the Finder and iTunes sidebar.

See pull request.

<img src="http://img440.imageshack.us/img440/1215/sidebarcolor.png">

**Comment by jordwalke** [comment]
I really like this. Vico pulled it off nicely.

**Comment by kjyv** [comment]
#84 seems related or solves part of this.

**Comment by kjyv** [comment]
400937eb introduces an option to use the current theme colors. The colors of the panel otherwise use [NSColor controlBackgroundColor] which is not the finder panel color (which is not directly defined) but it is the standard color for many list views. Also I think the finder sidebar is a different use cases, finder file trees look white and that color seems to be close or the same.
